import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navBar";
import Link from "next/link";
export default function Home() {
  return (
    <div className=" bg-gradient-to-r from-sky-900 to-violet-900">
      <Head>
        <title>Guilherme Tauil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/G.png" />
      </Head>

      <main className="">
        <Navbar />

        <div className="  w-auto sm:h-auto" id="Home">
          <div className="text-center p-5 sm:p-52">
            <h1 className="rounded-lg box-decoration-slice bg-gradient-to-r from-sky-900 to-violet-800 text-[30px] sm:text-[100px] font-bold font-mono">
              Guilherme Tauil
            </h1>
            <h2 className="cursor-pointer   sm:text-[30px]  decoration-slate-500 opacity-50 font-mono underline  sm:mt-10">
              Web developer front-end react.js and next.js
            </h2>
            <div className="  flex justify-center my-10 sm:my-20">
              <img className="  w-9 sm:w-60" src="g.png" />
            </div>
          </div>
        </div>
        <div id="Projetos" className="p-5">
          <h2 className="text-[30px] sm:text-[100px] font-bold font-mono text-center animate-pulse p-10">
            Projects
          </h2>
          <div className=" grid grid-cols-1 sm:grid-cols-3 sm:gap-4 content-center">
            <div className="hover:-translate-y-5  duration-500  my-5  cursor-pointer shadow-2xl backdrop-blur-sm   border border-opacity-30 border-gray-300 bg-opacity-5 text-center text-sky-900  rounded ">
              <img className=" sm:w-full" src="ia.jpg" />
              <div className=" p-5 border border-opacity-30 border-gray-300">
                <h3 className="text-slate-300">Title</h3>
                <p className="text-slate-500">Description</p>
              </div>
            </div>
            <div className="hover:-translate-y-5  duration-500  my-5  cursor-pointer shadow-2xl backdrop-blur-sm   border border-opacity-30 border-gray-300 bg-opacity-5 text-center text-sky-900  rounded ">
              <img className=" sm:w-full" src="ia.jpg" />
              <div className=" p-5 border border-opacity-30 border-gray-300">
                <h3 className="text-slate-300">Title</h3>
                <p className="text-slate-500">Description</p>
              </div>
            </div>
            <div className="hover:-translate-y-5  duration-500  my-5  cursor-pointer shadow-2xl backdrop-blur-sm   border border-opacity-30 border-gray-300 bg-opacity-5 text-center text-sky-900  rounded ">
              <img className=" sm:w-full" src="ia.jpg" />
              <div className=" p-5 border border-opacity-30 border-gray-300">
                <h3 className="text-slate-300">Title</h3>
                <p className="text-slate-500">Description</p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className=" backdrop-blur-sm   border border-opacity-30 border-gray-300 bg-opacity-5 bg-gray-800 flex flex-wrap justify-between  items-center p-10">
        <div>
          <Link href="#Home">
            <img className="cursor-pointer w-9 sm:w-20" src="G.png" />
          </Link>
        </div>
        <div className="">
          <p className="text-[10px] text-slate-200">
            Copyright © 2022 G, Inc. All rights reserved.
          </p>
        </div>
        <div className="flex">
          <Link href="https://github.com/GuilhermeTauil">
            <img
              className="cursor-pointer w-5 h-5 sm:w-10 sm:h-10 mx-3 "
              src="git-logo.png"
            />
          </Link>
          <Link href="#Home">
            <img
              className="cursor-pointer w-5 h-5 sm:w-10 sm:h-10   hidden sm:flex mx-3 "
              src="G.png"
            />
          </Link>
        </div>
      </footer>
    </div>
  );
}
